### ISSUE TITLE
aws cli is not installed on vm

### ISSUE THREAD

**Issue by APegaDavis** [SubhakarKotta/aws-eks-vagrant-ubuntu#1]
After deploying the ubuntu vm through vagrant the aws cli is not installed:
vagrant@aws-eks-ubuntu:~$ sudo su
root@aws-eks-ubuntu:/home/vagrant# aws configure

Command 'aws' not found, but can be installed with:

snap install aws-cli  # version 1.16.148, or
apt  install awscli

See 'snap info aws-cli' for additional versions.

root@aws-eks-ubuntu:/home/vagrant#

**Comment by s-u-b-h-a-k-a-r** [comment]
Fixed by adding awscli. It was broken with new ubuntu version 18.04
